pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}


include ':renpyiap', ':renpyandroid', ':app', ':ff1', ':ff2', ':ff3', ':ff4'

rootProject.name="app"